version: '2'

services:
  web:
    container_name: rs-web
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - API_PRIVATE_ENDPOINT=http://api:3080
    ports:
      - 8080:8080
    command: bash -c "yarn && yarn watch"

  api:
      container_name: rs-api
      build:
        context: ./api
        dockerfile: Dockerfile
      volumes:
        - ./api:/code    
      ports:
        - 3080:80      
      command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload 